steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=blog-ring
  - --key=blog-key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=config.js.enc
  - --plaintext-file=config.js
  - --location=global
  - --keyring=blog-ring
  - --key=blog-key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ca-certificate.crt.enc
  - --plaintext-file=ca-certificate.crt
  - --location=global
  - --keyring=blog-ring
  - --key=blog-key
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "600s"