steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=blog-ring
  - --key=blog-key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=config.js.enc
  - --plaintext-file=config.js
  - --location=global
  - --keyring=blog-ring
  - --key=blog-key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ca-certificate.crt.enc
  - --plaintext-file=ca-certificate.crt
  - --location=global
  - --keyring=blog-ring
  - --key=blog-key
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-blog-service:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-blog-service:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-blog-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/my-blog-service:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/my-blog-service:$COMMIT_SHA'