version: "2.3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - .env
    mem_limit: 300m
    mem_reservation: 100m
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  server:
    image: hassansaleh-blog
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - PGHOST=db
      - NODE_ENV=production
    mem_limit: 300m
    mem_reservation: 100m
